# Generated by Django 4.1.3 on 2023-01-03 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_trip_description_alter_trip_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='ativities_name',
            new_name='name',
        ),
    ]
