# Generated by Django 4.1.3 on 2023-01-03 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_name_expenses_activitites_expenses_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='trip',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.trip'),
        ),
    ]
