# Generated by Django 4.1.3 on 2023-01-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_expenses_time_alter_expenses_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
