# Generated by Django 4.1.3 on 2023-01-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_trip_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='status',
            new_name='Complete',
        ),
    ]
